'use strict';

/**
 * @ngdoc function
 * @name dh2321InformationVisualizationApp.controller:MainCtrl
 * @description
 * # MainCtrl
 * Controller of the dh2321InformationVisualizationApp
 */
angular.module('dh2321InformationVisualizationApp')
  .controller('MainCtrl', ['$scope', function ($scope) {

      $scope.labels =['Information Visualization', 'Statistics', 'Mathematics', 'Computer', 'Programming', 'Computer Graphics', 'Human Computer Interaction', 'User Experience'];

      $scope.sortType     = 'name'; // set the default sort type
      $scope.sortReverse  = false;  // set the default sort order
      $scope.search   = '';     // set the default search/filter term
      $scope.selectedGroup = 0;

      $scope.studentData = [
        {
          "degree": "Master in Science",
          "tolearn": "I expect to learn how to visualize different kind of data in an nice way. This to create something beautiful to the users. \n\nAlso I want to learn different techniques related to visualizing data and concepts of how to do it good. ",
          "visskills": 6,
          "statsskills": 7,
          "mathskills": 5,
          "drawskills": 5,
          "compskills": 7,
          "progskills": 7,
          "cgskills": 5,
          "hciskills": 6,
          "uxskills": 7
        },
        {
          "degree": "Bachelor in Science",
          "aboutyourself": "I like playing with data in intuitive ways",
          "tolearn": "No idea, sort of my first course in it.",
          "visskills": 5,
          "statsskills": 4,
          "mathskills": 5,
          "drawskills": 2,
          "compskills": 10,
          "progskills": 7,
          "cgskills": 6,
          "hciskills": 4,
          "uxskills": 1
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "My current interests include:\nFitness/lifting weights(theory)\nProgramming in general\nFunctional programming\nProgramming language theory\n\nMy hobbies include:\nFitness/lifting weights\nWatching competetive video games\nPlaying competetive video games\nProgramming\nPlaying the guitar",
          "tolearn": "I expect to learn methods and theory for visualizing different types of information. I also expect to pick up some frameworks for visualizing information, and also general methods of programming for visualizing information.\n\nI think think that by learning how to visualize information I will also learn how to reason about information in terms of how it can be utilized in more effective ways. While I might not always have to visualize information, being able to have better thought patterns in regard to it will be useful in pretty much any data driven task.",
          "visskills": 4,
          "statsskills": 4,
          "mathskills": 5,
          "drawskills": 6,
          "compskills": 8,
          "progskills": 8,
          "cgskills": 3,
          "hciskills": 5,
          "uxskills": 5
        },
        {
          "degree": "Bachelor in Science",
          "tolearn": "To visualize information in 3D space",
          "visskills": 1,
          "statsskills": 5,
          "mathskills": 5,
          "drawskills": 8,
          "compskills": 8,
          "progskills": 8,
          "cgskills": 5,
          "hciskills": 7,
          "uxskills": 8
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "I enjoy video games and hiking, and my major hobby is LARPing (lajv in swedish). I do most genres, from blackbox (small events that usually only lasts for an hour or two and are preformed in an almost bare enviorment) to full scale, weeklong historical fantasy war scenarios. I am also somewhat involved in arranging a couple of scenarios that have not been played yet.\n\nI like games of various types, and I feel that they are a great learning strategy.",
          "tolearn": "I have no idea what i will learn, I chose this course almost by random. Therefore I dont really know what I expect or what I will do with it.",
          "visskills": 4,
          "statsskills": 2,
          "mathskills": 4,
          "drawskills": 5,
          "compskills": 8,
          "progskills": 5,
          "cgskills": 3,
          "hciskills": 5,
          "uxskills": 6
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "My main interests are music and training. I play guitar and sing in a band called Bear With Us, check us out on Spotify!",
          "tolearn": "I don't have any expectations really but I have been told that it is a good course. I hope I get to learn more about visualization design and programming ",
          "visskills": 3,
          "statsskills": 6,
          "mathskills": 6,
          "drawskills": 3,
          "compskills": 7,
          "progskills": 5,
          "cgskills": 3,
          "hciskills": 3,
          "uxskills": 5
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "Video games, dancing, food",
          "tolearn": "Making neat graphical representations of data. I want to work with data analysis and I expect to use what I learn for that.",
          "visskills": 3,
          "statsskills": 10,
          "mathskills": 9,
          "drawskills": 7,
          "compskills": 8,
          "progskills": 7,
          "cgskills": 4,
          "hciskills": 7,
          "uxskills": 5
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "Games, books, comics, music",
          "tolearn": "How to better visualise information. Not sure. I think it's an interesting subject, that's all. ",
          "visskills": 5,
          "statsskills": 4,
          "mathskills": 6,
          "drawskills": 3,
          "compskills": 8,
          "progskills": 7,
          "cgskills": 5,
          "hciskills": 9,
          "uxskills": 4
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "photographing, drawing, graphic design, postcard collecting and making, traveling, swimming, badminton",
          "tolearn": "Learn theories and techniques in visualising information for creating well-structured and innovative visualised representation of unstructured information. Build up the concept of information visualisation and be able to  apply the techniques later in industry or academia.",
          "visskills": 4,
          "statsskills": 5,
          "mathskills": 7,
          "drawskills": 8,
          "compskills": 9,
          "progskills": 7,
          "cgskills": 5,
          "hciskills": 5,
          "uxskills": 6
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "I'm intreseted in creating useable products for everyone. On my sparetime I like being out in the nature and both doing sports myself and coaching children.",
          "tolearn": "I expect to learn new ways of showing data to people in  different ways both to enhance understanding and make it look intresting. I belive that good visualzation of informatin can help people to make the right decisions with a deeper understanding in the actual data.",
          "visskills": 4,
          "statsskills": 6,
          "mathskills": 6,
          "drawskills": 4,
          "compskills": 8,
          "progskills": 6,
          "cgskills": 4,
          "hciskills": 7,
          "uxskills": 6
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "I like sports. Mainly tennis and football ",
          "tolearn": "I hope to developers my graphical knowledge which I think is valuable for the future",
          "visskills": 2,
          "statsskills": 8,
          "mathskills": 6,
          "drawskills": 3,
          "compskills": 8,
          "progskills": 7,
          "cgskills": 2,
          "hciskills": 2,
          "uxskills": 6
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "I am a student of media technology and I love movies and video games. I am mostly interested in storytelling, narrative and world-building in all arts, mostly the visual, and also level design in video games.",
          "tolearn": "I expect to learn how to draw users attention to the wanted information and how to represent raw data in a way that's easy and relevant for the user, plus more that I probably haven't thought of yet.",
          "visskills": 3,
          "statsskills": 5,
          "mathskills": 7,
          "drawskills": 4,
          "compskills": 7,
          "progskills": 2,
          "cgskills": 3,
          "hciskills": 3,
          "uxskills": 2
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "I am a Master student in EIT Digital's Human Computer Interaction and Design. I have 3+ years of work experience and I like coding.",
          "tolearn": "Different ways of how visualisation can be used to analyse data. How to do them. Create some beautiful visualisations on mobile phones.",
          "visskills": 3,
          "statsskills": 5,
          "mathskills": 4,
          "drawskills": 5,
          "compskills": 8,
          "progskills": 7,
          "cgskills": 3,
          "hciskills": 4,
          "uxskills": 7
        },
        {
          "degree": "Master in Science",
          "tolearn": "I expect to learn the methods and tools that I can use for data mining and data visualization.",
          "visskills": 3,
          "statsskills": 4,
          "mathskills": 3,
          "drawskills": 7,
          "compskills": 9,
          "progskills": 4,
          "cgskills": 3,
          "hciskills": 7,
          "uxskills": 9
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "I have been studying computer science but decided to go with human computer interaction for the master rather than computer science, since I prefer the front end part of the computer science, as well as interaction design. I have an overall interest in technology and technological solutions. Other than technological interests, I like sports (ice-hockey, football, etc.), computer games etc. ",
          "tolearn": "I expect to learn how to better visualize information and design interactive interfaces. By doing so, I hope to get a wider scope of usable tools for such interfaces, and how to use them, as well as when not to use them. Furthermore, I hope by finishing  the project I will become a better programmer, designer and project member and/or leader. A bonus would be to have a project result worth putting in my portfolio. ",
          "visskills": 3,
          "statsskills": 4,
          "mathskills": 5,
          "drawskills": 1,
          "compskills": 5,
          "progskills": 6,
          "cgskills": 4,
          "hciskills": 6,
          "uxskills": 6
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "I'm a graphic designer and illustrator. I also work with digital media and user experience design. I'm interested in art and photography. Apart from working out in the gym, reading and watching movies are my hobbies. Plus, I like travelling and visiting art galleries. ",
          "tolearn": "I expect to get insight and the proper way of visualising information. As I'm passionate about graphic design and art, visualising information is very intriguing to me. I may use the tools that I learn from this course to help me when it comes to presentation. ",
          "visskills": 6,
          "statsskills": 2,
          "mathskills": 2,
          "drawskills": 9,
          "compskills": 9,
          "progskills": 5,
          "cgskills": 2,
          "hciskills": 2,
          "uxskills": 5
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "Computer Games, League of Legends, Psychology, Reading, Gamification, Hiking",
          "tolearn": "Learning how to visualize and understand vast amounts of data. Use it for visualizing human behaviour and identify pattern. Visualizing game data. Make visualizations which help us to understand the world better.",
          "visskills": 5,
          "statsskills": 5,
          "mathskills": 2,
          "drawskills": 4,
          "compskills": 9,
          "progskills": 5,
          "cgskills": 1,
          "hciskills": 5,
          "uxskills": 4
        },
        {
          "degree": "Bachelor in Science",
          "aboutyourself": "test",
          "tolearn": "test",
          "visskills": 1,
          "statsskills": 1,
          "mathskills": 1,
          "drawskills": 1,
          "compskills": 1,
          "progskills": 1,
          "cgskills": 1,
          "hciskills": 1,
          "uxskills": 1
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "I am into UX design. Love to explore with projects in different domains and platform. Looking forward for the opportunity to play around with oculus rift in the course ;P\n\nApart from this I love to play basketball and squash. Also I am pretty good in cooking Indian meals :)",
          "tolearn": "From this course I want to learn the technique to take out meaning out of numbers and then create their representation for simple representation.\n\nKey things to get out :\n- how to interpret data \n- tools to use\n- current practices\n",
          "visskills": 6,
          "statsskills": 4,
          "mathskills": 6,
          "drawskills": 6,
          "compskills": 8,
          "progskills": 6,
          "cgskills": 6,
          "hciskills": 7,
          "uxskills": 8
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "I love reading about humand mind, how we precieve, understand things, make decisions etc. As I did my Bachelor in International Business economic hirtory is also one of the main subjects I read about. Lately I have have started to read about business analysis and interactin design as that is really closely related to my work as an analyst in an software development company. ",
          "tolearn": "I mainly hope to use the skills in my job working as an analyst. I hope that it will enable me to suggest visully easier to grasp information presentation and therefore give my company's work as an analys a competitive advantage over the regular IT solution. \n\nIn addition to that I hope that that will enable me to make a better framework to analyse the analysing process itself in our company. Our hopes are that we could develop a fairly concrete framework which could hel our future analysts to start off their work. It is very important tat the framework or its key pillars would be visiually easily graspable. ",
          "visskills": 4,
          "statsskills": 3,
          "mathskills": 7,
          "drawskills": 8,
          "compskills": 6,
          "progskills": 2,
          "cgskills": 1,
          "hciskills": 1,
          "uxskills": 3
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "I am a two year master student. My passion is game design and visualization. I have some knowladge about modeling and design some I have learned in lectures some I learned by myself (unity, blender, 3DS Max, photoshop etc) . I am really interested in computer games (not indie games rather big games with graphics ). I am interested in animation creation and simulation with 3d objects. ",
          "tolearn": "I expect to learn about creating interactive applications either to web or other platform. I expect to gain deeper insight about visual models and how to develop such models. \nI expect to use information I learned here developing commercial applications. ",
          "visskills": 6,
          "statsskills": 3,
          "mathskills": 4,
          "drawskills": 3,
          "compskills": 6,
          "progskills": 6,
          "cgskills": 4,
          "hciskills": 4,
          "uxskills": 2
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "I think technology in general is very interesting, the different possibilities it creates and how it changes the way we act and communicate. Coincidentally, I like to read about new tech, gadgets, software and whatnot.\n\nI like to work creatively with design and different sorts of software development (usually web), which are also some of my hobbies. Other than that, I like gaming, exercising, and hanging out with friends. Of course also long walks in the moonlight and cozy couch-evenings!",
          "tolearn": "I expect to learn of new ways of visualizing information (shocker!), what's important as you do and how I could be able to incorporate this knowledge into both my hobby and my professional work.\n\nI would like to learn more JS and ways of displaying information on the web as well as \"offline\" such as infographics, charts and maybe even in video as that is one of my interests as well.",
          "visskills": 5,
          "statsskills": 3,
          "mathskills": 3,
          "drawskills": 7,
          "compskills": 9,
          "progskills": 5,
          "cgskills": 2,
          "hciskills": 7,
          "uxskills": 5
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "My hobbies are games (computer and console) and drawing. I also like reading, especially fantasy and science fiction.",
          "tolearn": "I expect to learn different methods and ways of presenting and visualizing information, which will probably be very useful no matter what I'll be working with in the future. ",
          "visskills": 4,
          "statsskills": 3,
          "mathskills": 6,
          "drawskills": 9,
          "compskills": 9,
          "progskills": 6,
          "cgskills": 4,
          "hciskills": 7,
          "uxskills": 7
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "I like graphical interfaces and how to visualize data, which of course is perfect for this course. I like new challenges and met new people to work with. I am hard working and likes to learn new stuff. \nI know how to program, I only have some experiences from web programming such as html, css.",
          "tolearn": "How to approach when visualize data, what to think about, maybe if there is certain guidelines for when to use certain methods. \nI would like to learn as much as I can since i am really amused and inspired about this area, and really wants to take the most from this course. \nI really like visualization and are planing to maybe do something with it in my master thesis, depending on how I feel after this course. ",
          "visskills": 5,
          "statsskills": 5,
          "mathskills": 6,
          "drawskills": 6,
          "compskills": 5,
          "progskills": 7,
          "cgskills": 4,
          "hciskills": 7,
          "uxskills": 8
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "In my free time I play a lot of computer games and I'm interested in game design and level design as well as programming. For this reason I like to create custom levels for  games I like and create simple games. Non computer related: I do indoor climbing as a hobby.",
          "tolearn": "I expect to learn how to visualize data in a way thats easy to perceive and interact with. \nThis should be useful whenever I want someone to understand a lot of data. It could help in creating a game's graphical user interface if I know of good ways to show information to the user.",
          "visskills": 4,
          "statsskills": 7,
          "mathskills": 7,
          "drawskills": 4,
          "compskills": 7,
          "progskills": 6,
          "cgskills": 6,
          "hciskills": 9,
          "uxskills": 4
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "Interests I'm hoping to bring to this course include storytelling, music, and gaming. I'd say I'm generally leaning more toward the conceptual side of things, but of course I also want to learn how to bring those concepts to life. ",
          "tolearn": "I expect there'll be a fair amount of programming, but the main thing I want to learn is how to present information in a clear, concise way. I think the ability to do that would be immensely useful in many facets of life, not to mention working in HCI. ",
          "visskills": 4,
          "statsskills": 4,
          "mathskills": 5,
          "drawskills": 4,
          "compskills": 5,
          "progskills": 5,
          "cgskills": 4,
          "hciskills": 7,
          "uxskills": 5
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "- 26 y.o.\n- From Stockholm (Sollentuna)\n- Bachelor in Business Administration from Uppsala University.\n- Studied one year in Santa Barbara (2008-2009)\n- Studied half a year in Canberra (2013)\n- Studied Media technology (2014-2015) at KTH (mostly math and programming classes)\n\n- Interested in working on important/fun projects.\n- Excelling in my work area of life is very important to me.\n\n- General interest in how things work. More specifically how societies and people function. I have taken some university classes in psychology, biology and archaeology.\n\n- I like categorizing things, and I think that's my strongest cognitive ability (relative to memory, arithmetic, spatial etc). Hope that will be helpful in Information Visualization.\n\n- Don't have to much time for hobbies anymore. School, work and my girlfriend fill most hours. I like snowboarding/skiing in the winter. Adventure sports in general are fun (scuba diving, hiking, climbing, cross-country skiing, wakeboarding, motorboats). Played a lot of video/PC-games in my teens (strategy or adventure games mostly). Mostly read video-games magazines now days to keep up on the progress of the industry.\n\n- Used to shoot and edit movies in my teens. Also animate movies in Adobe (Macromedia) flash. Something I've been thinking on starting doing again.\n\n- Have used photoshop and Corel Draw (Illustator substitute) for a t-shirt company I ran some few years ago.\n\n- Have been apart of Excitera (entrepreneurship society at KTH) for one year. Now sits as the Vice president. Have a general interest in Startups, and I will probably try to create a business myself some day.\n\n",
          "tolearn": "- How to technically create useful visualizations of data.\n- How to theoretically create useful visualizations of data.\n- How to cooperate in a project with more than 4 persons.\n\nI expect to utilize this experience and knowledge in future work projects.",
          "visskills": 7,
          "statsskills": 5,
          "mathskills": 7,
          "drawskills": 7,
          "compskills": 8,
          "progskills": 5,
          "cgskills": 6,
          "hciskills": 5,
          "uxskills": 7
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "My biggest interests are video games and drama. I have been a hobby actor for a little more than a decade, and in later years I have also tried out directing and writing.",
          "tolearn": "I expect to become Hans Rosling. Or at least getting a step further in becoming him.",
          "visskills": 4,
          "statsskills": 5,
          "mathskills": 8,
          "drawskills": 1,
          "compskills": 7,
          "progskills": 4,
          "cgskills": 2,
          "hciskills": 4,
          "uxskills": 9
        },
        {
          "degree": "Bachelor in Science",
          "aboutyourself": "Hey You!\n\n----------------\nWhat I like:\n----------------\nI am a person who enjoys to improve a non-finished product. It can be anything from an idea, concepts, prototypes or softwares to a better, more appealing, better user experience, \"this is the way this product should be\" way. \n\nI also like to brainstorming and come up with unique ideas to reach where we really want. (Because great ideas usually does not come out of the blue).\n\n------------------------------\nWho I work best with:\n------------------------------\nI work best with people who does not care about small things and wants to go forward and sees on the bright side of the project. I also work good with people who criticises ones idea to make so that it is possible to come up with even better ideas!\n\n------------------------------------------------\nWhat I expect during a group work\n------------------------------------------------\nDuring a group work, I want to have conversations that converge us towards our best goal and solutions, rather converging to someones \"best goal\" .\n\n---------------\nMy hobby\n---------------\nI have a unique hobby such as performing a magic (works as magician) and play ukulele, and I enjoy to ramble.",
          "tolearn": "I want to learn different/unique way of using the 3D printer. \n\nSome examples are print out some dynamic shapes, for instance wave of a sound, music, or a plot of a chaotic system.",
          "visskills": 1,
          "statsskills": 4,
          "mathskills": 6,
          "drawskills": 5,
          "compskills": 5,
          "progskills": 4,
          "cgskills": 3,
          "hciskills": 2,
          "uxskills": 8
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "I am graduate in multimedia engineering expert in videogames, gamification and HCI. My final bachelor thesis was a videogame using low cost electronic sensors, my role was the main developer. I also did a master in Gamification and Serious Gaming which ended with a Master thesis which was a serious game for Android devices developed for a real company. \n\nMy hobbies are: playing videogames, sci-fi and fantasy reading, painting miniatures and digital photography. ",
          "tolearn": "I expect to further increase my programming skills and use some statistics on it to achieve nice visualization interfaces. I am very interested in producing some generative art interfaces where the user could interact with a visual interface and generate art. ",
          "visskills": 5,
          "statsskills": 4,
          "mathskills": 5,
          "drawskills": 7,
          "compskills": 9,
          "progskills": 8,
          "cgskills": 8,
          "hciskills": 10,
          "uxskills": 9
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "I like to learn new things. Nowadays I am trying to have a more conscious life, doing things like yoga, diet and reading about psychology. In HCI, I am interested in the ways technology can be used to help people to have a more meaningful life.",
          "tolearn": "I am curious about the topic, but I have a very vague idea for which purposes it can be used for. I think it can be an interesting skill to have in the future, it also seems cool to create images based on data.",
          "visskills": 2,
          "statsskills": 5,
          "mathskills": 7,
          "drawskills": 3,
          "compskills": 7,
          "progskills": 5,
          "cgskills": 3,
          "hciskills": 5,
          "uxskills": 7
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "The whole process of creating a video game, also programming.",
          "tolearn": "I expect to learn about d3.js and also different and creative ways of presenting information for the viewer/user.",
          "visskills": 4,
          "statsskills": 7,
          "mathskills": 5,
          "drawskills": 8,
          "compskills": 10,
          "progskills": 8,
          "cgskills": 4,
          "hciskills": 5,
          "uxskills": 5
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "I am an IT student who has a lot of interest in the humanities. I have studied half a year of History of Art and half a year of Practical Philosophy at the side of my engineering studies at KTH. I think my main interest lies in gender studies when it comes to what I'm reading on the train to and from school, but I also really enjoy reading about art.\n\nI also have an interest in technology. As someone coming from the IT program I think I've been kind of colored by the people interested in low level programming. I'm kind of missing the ASM and C work we did back in the Computer Technology (?) course. (I'm kind of looking at how it is to work with a Gameboy in my spare time.)\n\nAs for more conventional hobbies I guess I like to play games? But lately it has been more reading about games as an art form than actually playing them. Reading about art is something I find really interesting.\n\nI also listen to a lot of music, be it while I studying alone, while I travel to school/home, when I play games, or doing nothing else. I can enjoy more \"difficult\" music that requires focus to enjoy, as well as more conventional music. I really liked the \"The Fetus Speaks\" project as a concept. (And maybe less the heternormativity found in the video presenting the project.)\n\nAlso waste too much time on youtube.",
          "tolearn": "I hope to broaden my knowledge of how I can visualize information in different ways, and knowledge of which qualities are fitting for which situations. I hope to both learn methods and tools for information visualization as well as critical reflection on current (or past) practice within the field.\n\nI expect to use what I learn mainly for improving my own presentation of information in software solutions and academic work that I produce. I also hope to use this knowledge when assessing both the suitability for IV solutions I come across in my everyday life; finding bad (and good) designs in life can be quite fun.",
          "visskills": 6,
          "statsskills": 4,
          "mathskills": 8,
          "drawskills": 2,
          "compskills": 7,
          "progskills": 7,
          "cgskills": 6,
          "hciskills": 7,
          "uxskills": 7
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "A lot of things within creativity, i.e. art (drawing) and music (both listening to and producing some of my own). This creativity can definitely be used towards fueling my interest for designing intuitive and interesting user interfaces.",
          "tolearn": "To create interactive visualized informative systems, that can be demonstrated once fully developed. To reach this goal in a group is also something that I strive to achieve. Once learned, this experience can be used towards working in similar areas after graduation.",
          "visskills": 6,
          "statsskills": 5,
          "mathskills": 5,
          "drawskills": 7,
          "compskills": 7,
          "progskills": 5,
          "cgskills": 4,
          "hciskills": 5,
          "uxskills": 6
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "I studied Computer Science back in France for two years (equivalent to my third year of bachelor and first year of master), but I'm not that skilled in programming. \nI really like graphic design and art, and I'm very interested in seeing how technology shapes new forms of art and inspiration everyday!",
          "tolearn": "I want to learn… \n1. how to visualize data in a way that's appealing for experts and for new users alike \n2. about the trends in information visualization, what can and has been done\n3. find a way to shape visualization not only for it to be pretty but also relevant, and explain or defend these choices\n4. how to scale and select data in a relevant way from formatted data available online\n",
          "visskills": 4,
          "statsskills": 1,
          "mathskills": 3,
          "drawskills": 8,
          "compskills": 8,
          "progskills": 3,
          "cgskills": 3,
          "hciskills": 3,
          "uxskills": 3
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "About me as a person I can say that I am not shy but neither I am very social. I have a knack for problem solving but often I have a hard at time convincing people to try my solutions. You see, I am not an eloquent person and it is difficult for me to express myself through speech even though I am actually skilled at writing. \n\nOf all senses of the human body, vision is my favourite one. I believe that visual media are some of the most powerful at our disposal, in terms of speech and information density. A good narrative should nonetheless never be underestimated, as I believe that people process information best in story form. In my opinion information should not only be conveyed but also entertaining and memorable as well.\n\nWhy am I telling you this? Because I have two main hobbies: I paint and I write. Originally, I liked to oil-paint and charcoal or pastel-draw, but nowadays I mostly paint-digitally. In terms of writing it is creative writing that I do, mostly in the form of novels or short stories.",
          "tolearn": "How to create visualisation interfaces that are able to present raw numerical data into a human-friendly fashion that is more easily interpretable.",
          "visskills": 5,
          "statsskills": 5,
          "mathskills": 7,
          "drawskills": 10,
          "compskills": 10,
          "progskills": 6,
          "cgskills": 8,
          "hciskills": 6,
          "uxskills": 3
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "I am an international student doing my masters in HCID, EIT Digitals. Knowledge and information that can could be obtained through data visualization has always amazed me. I am keen in learning techniques and technologies through which I can unravel the power of information visualization. I like travelling and exploring the nature. ",
          "tolearn": "I expect to learn different techniques and technologies to enhance the visualization of information and also provide greater degree of assessment and customization on the visualized data. ",
          "visskills": 7,
          "statsskills": 5,
          "mathskills": 5,
          "drawskills": 5,
          "compskills": 8,
          "progskills": 6,
          "cgskills": 3,
          "hciskills": 4,
          "uxskills": 7
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "film, traveling, photography",
          "tolearn": "infographic; motion graphic; to make news/stories more readable",
          "visskills": 1,
          "statsskills": 6,
          "mathskills": 6,
          "drawskills": 2,
          "compskills": 7,
          "progskills": 1,
          "cgskills": 1,
          "hciskills": 1,
          "uxskills": 6
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "I'm interested in all sorts of programming. Mainly towards games and visualization, which is probably because I've tried most other areas in programming and feel they don't quite scratch my itch, so to speak.\n\nI'm also really into boardgames: Carcassonne, Dominion and Munchkin to name a few. They reflect my fascination with tactics, strategies and logic, but most importantly the social factor of being with friends and off the screens.\n\nI also like to delve deep into any new project spanning 1-5 months, may it be woodworking, painting, growing herbs, or anything else really. Probably due to me liking to learn new things, especially if they catch my interest.",
          "tolearn": "I expect to get a good foundation in how to visualize information, which I can then build onto later in my career.\n\nI hope to be able to use it in my future work to help my team/company to present large/huge amounts of data in new ways that are more intuitive and show relations clearly between them.\n\nI also hope to get some experience in new programming styles/languages/libraries to add onto my programming knowledge.\n\nAlso to improve my experiences of working in projects and presenting in front of crowds.",
          "visskills": 3,
          "statsskills": 3,
          "mathskills": 4,
          "drawskills": 4,
          "compskills": 8,
          "progskills": 8,
          "cgskills": 5,
          "hciskills": 5,
          "uxskills": 4
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "My hobbies include drawing and modeling (mostly in Maya). I like sports and play floorball in my sparetime.",
          "tolearn": "I expect to learn how to combine and present data in an interactive and interesting way. It should be of use in multiple areas, for pretty much every application that deal with large sets of data.",
          "visskills": 3,
          "statsskills": 4,
          "mathskills": 6,
          "drawskills": 8,
          "compskills": 8,
          "progskills": 5,
          "cgskills": 6,
          "hciskills": 8,
          "uxskills": 5
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "Art related development;\nCutting edge technology;\nInnovative ideas",
          "tolearn": "Manage information into a organised way. Basic sense of design in visualisation.\n\nPresent data in an impressive way; Design an interface with clear information architecture.",
          "visskills": 3,
          "statsskills": 8,
          "mathskills": 8,
          "drawskills": 2,
          "compskills": 7,
          "progskills": 6,
          "cgskills": 5,
          "hciskills": 7,
          "uxskills": 9
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "Emil, 24 year old. Born and raised in Stockholm. When not studying at KTH, I play in a band together with 3 course mates. We're called 'Bear With Us' - you should check us out, we're on spotify - and I play drums and some background singing! I also watch a whole lot of drama series, ranging from real bad sci-fi to documentaries and really enjoy the time off to just relax the brain a bit. I also have a bit of a peculiar hobby called 'origami', the art of folding paper, which I practiced a lot some years ago. I don't do it much today, but I try to keep my skill up by folding different stuff on a regular basis!\nI'm also interested in HCI and media interaction, especially web based interaction, and hope to work with something in this area when I graduate from KTH in two years.",
          "tolearn": "I expect to learn a lot on what different kind of tools there is that I can use when design and visualize data. I'm also expecting to work with some of the really cool technologies that the VIC-studio can provide, and develop an application which I can use for future job application as part of a portfolio. I want to have a solid foundation for how one visualizes things in the best way and to be able to both give and receive feedback on peoples work.",
          "visskills": 5,
          "statsskills": 6,
          "mathskills": 7,
          "drawskills": 4,
          "compskills": 8,
          "progskills": 6,
          "cgskills": 6,
          "hciskills": 8,
          "uxskills": 7
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "In my free time I usually do aerobics, I also like reading, hanging with my friends, and going to rock & metal concerts.",
          "tolearn": "I expect to learn some new and useful approaches and tools for data visualization. I think that there are many areas where it is vital to present the data in an easily understandable way, and if once I'll have to work with large data sets it can be a useful knowledge.",
          "visskills": 5,
          "statsskills": 4,
          "mathskills": 5,
          "drawskills": 3,
          "compskills": 8,
          "progskills": 1,
          "cgskills": 1,
          "hciskills": 2,
          "uxskills": 1
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "I like taking adventures and try new things. Since I have several hobbies, such bamboo flute, drawing, cooking, hip-pop, biking and photography, I totally enjoy my life. I will explore more fantastic thing, and work to become a story teller, life recorder and HCI designer in future :)",
          "tolearn": "How to use some practical tools to present data in an informative and attractive way, as well as some techniques in visualization",
          "visskills": 7,
          "statsskills": 6,
          "mathskills": 4,
          "drawskills": 8,
          "compskills": 8,
          "progskills": 7,
          "cgskills": 7,
          "hciskills": 7,
          "uxskills": 8
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "-Interested in product, especially high-tech product. \n-The major in bachelor is industrial design, which trained my aesthetic and taught me human-centered research.\n-Also studied financial engineering as double bachelor degree. Thus be able to do general statistic analysis.\n-Really enjoy the life with Internet, electronic devices, sports and music. \n",
          "tolearn": "I hope to gain ability to program for information visualization because I'd like to link it with my future job and it gradually become a indispensable part of internet company.\n",
          "visskills": 5,
          "statsskills": 5,
          "mathskills": 5,
          "drawskills": 7,
          "compskills": 8,
          "progskills": 2,
          "cgskills": 3,
          "hciskills": 3,
          "uxskills": 7
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "GAMES. I live and breathe games. I attend every possible game jam, AAA tile release, trying my best to follow Nvidia/E3/GDC and hardware development announcement.\nSeems like I have a thing for programming languages as well. I can discuss Haskell semantics, why Clojure is excelling in multiple fields but will never become a big thing and my affection for Javascript, who I will defend it in a oo so hateful world.\nI'm also that kind of guy who loves his terminal, mechanical keyboard and custom text editor a little bit too much.\nGraphics is a newly rediscovered love of mine. Lately I've read up on and practiced physically based rendering and the associated texture workflows. ZBrush <3.",
          "tolearn": "Learn some concepts, techniques and algorithms for information visualization. These learning outcomes could empower me to create more engaging experiences in games and apps, and hopefully uncover some otherwise invisible and valuable facts in the data.",
          "visskills": 7,
          "statsskills": 4,
          "mathskills": 7,
          "drawskills": 5,
          "compskills": 10,
          "progskills": 8,
          "cgskills": 8,
          "hciskills": 9,
          "uxskills": 5
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "I am a Chinese girl who like drawing, singing and doing sport (like badminton,swimming and so on). I like to talk with people to know different life experience and attitude, and I sometimes  do personality- analysis of people I meet due to the interest for psychology. But that is all about guess. What's more, I like to learn new and creative things, as well as try new things to get different experience. ",
          "tolearn": "I expect to learn to how to collect the data in an efficient way and how to analyses the result we have got and present the data in an effective, understandable and beautiful way.\nI want to use it in my portfolio(personal web) and have it as my skill in further studying related to HCI.",
          "visskills": 5,
          "statsskills": 6,
          "mathskills": 5,
          "drawskills": 8,
          "compskills": 8,
          "progskills": 5,
          "cgskills": 5,
          "hciskills": 6,
          "uxskills": 7
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "Badminton. Travelling. Shopping.",
          "tolearn": "I expect to learn how to make complicate information easier for more people to understand. \nUse it to make better presentations. Develop applications that can help people make better presentations.",
          "visskills": 2,
          "statsskills": 4,
          "mathskills": 6,
          "drawskills": 1,
          "compskills": 9,
          "progskills": 8,
          "cgskills": 9,
          "hciskills": 10,
          "uxskills": 1
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "I did my Bachelor degree in Computer Science. I have worked for two years as a developer for a company that develops complex web applications. I worked on a few corporate sites, an automatic GUI testing framework and I set up the company's SharePoint-based ticket system. For my bachelor thesis I've developed a software generator that can dynamically generate backend maintenance screens based on a database structure and user input (using .NET, Razor and AngularJS)\n\nIn my free time I have several hobbies including (but I'm sure I forget some) climbing, hiking, camping, photography, board games, computer games, reading.",
          "tolearn": "I'm expecting to learn how to analyze data and visualize this data to provide extra/easier insight into the data. This will help users analyzing data or it will make data manipulation easier.\n\nI think this will be very useful in future HCI projects because a good visualization has a very big influence on the user experience. That's why I expect to use what I learn here in almost every project that I will do afterwards.\n\nI also expect to learn a lot from my fellow students coming from different fields. And the competitive environment of the C-awards is also something I'm looking forward to. I think it will motivate me to put even more effort into the project.",
          "visskills": 8,
          "statsskills": 5,
          "mathskills": 8,
          "drawskills": 4,
          "compskills": 8,
          "progskills": 8,
          "cgskills": 8,
          "hciskills": 8,
          "uxskills": 7
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "I love moving my body either through team sports, extreme sports or just working out. Though it's a hobby I don't spend much time with lately photography and filmmaking have for a long time been interests of mine, being able to see or envision something and then try to create or capture it.",
          "tolearn": "I hope to gain more tools for visualizing things that might otherwise be hard to understand through intuitive and cool ways.",
          "visskills": 6,
          "statsskills": 3,
          "mathskills": 5,
          "drawskills": 5,
          "compskills": 7,
          "progskills": 2,
          "cgskills": 3,
          "hciskills": 7,
          "uxskills": 4
        },
        {
          "degree": "Master in Science",
          "tolearn": "I expect to learn data representation, information design and visual analysis. I expect to use what I learn to expand my repertoire.",
          "visskills": 3,
          "statsskills": 3,
          "mathskills": 3,
          "drawskills": 2,
          "compskills": 7,
          "progskills": 7,
          "cgskills": 3,
          "hciskills": 6,
          "uxskills": 2
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "I like both learning and creating. My interests are language, drawing, home decoration and games.",
          "tolearn": "I have a lot of ideas but a difficulty to realize them. So I hope I will learn how to use the right tools and working process.",
          "visskills": 4,
          "statsskills": 6,
          "mathskills": 5,
          "drawskills": 8,
          "compskills": 7,
          "progskills": 5,
          "cgskills": 3,
          "hciskills": 4,
          "uxskills": 5
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "I really like discovering new things, being challenged. It's a way for me to overcome my boundaries. \nI like skating, swimming, listening music, watch movies. ",
          "tolearn": "Up to now, I have never worked on project related to information visualisation. I expect to learn different methods and techniques to visualize information because I think that it could be interesting and relevant to have some notions in today's work world. ",
          "visskills": 3,
          "statsskills": 3,
          "mathskills": 8,
          "drawskills": 7,
          "compskills": 8,
          "progskills": 4,
          "cgskills": 6,
          "hciskills": 5,
          "uxskills": 5
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "I moved from Gothenburg 5 years ago to study at KTH in Stockholm. \nBesides studies, I have engaged in different side projects such as Next Up Stockholm, Armada and today I’m business manager in a non-profit organization called Womengineer. Our goal is that by year 2030, we want 50% of all graduated engineers in Sweden to be women. This is the far best project i’ve involved in, together with the rest of our members we work hard to reach our goal. \nI am interested in designing, prototyping, creating and evaluating multimedia information to serve different users. I have also a big interest in psychology in the area of trying to understand the users behaviours regarding the use of provided information. I hope that I someday can make people’s everyday life easier than it is today by the help of my technical background studying CS and socio-technical background studying HCI. \n",
          "tolearn": "Throughout this course, i’d really like to get a better understanding and knowledge within user-centered design and visual analysis. From this course I hope that I can take the 5 learning outcomes, especially 2-5, to my future work. \n",
          "visskills": 5,
          "statsskills": 5,
          "mathskills": 7,
          "drawskills": 7,
          "compskills": 7,
          "progskills": 4,
          "cgskills": 4,
          "hciskills": 5,
          "uxskills": 7
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "I don't have any particular hobbies, but I like being active within the Media Technology chapter by, for example, playing sports or going to pubs.",
          "tolearn": "Learn more about information visualization systems; how and why are they designed as they are? What makes a good/bad information visualization system? And of course - have fun learning it!",
          "visskills": 1,
          "statsskills": 2,
          "mathskills": 4,
          "drawskills": 2,
          "compskills": 5,
          "progskills": 1,
          "cgskills": 1,
          "hciskills": 1,
          "uxskills": 2
        },
        {
          "degree": "Bachelor in Science",
          "aboutyourself": "I am interested in graphics and animations. In general I could say that I like travelling, photography and yoga.",
          "tolearn": "The subject of the course is completely new to me and sounds very interesting. I' ll do my best to learn as more as I can. I expect to enhance my skills in graphics and human computer interaction.",
          "visskills": 2,
          "statsskills": 2,
          "mathskills": 4,
          "drawskills": 7,
          "compskills": 8,
          "progskills": 3,
          "cgskills": 3,
          "hciskills": 3,
          "uxskills": 2
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "I am crazy about cooking and also love traveling and watching movies.",
          "tolearn": "I expect to learn interesting methods to translate complex and even statistic data into interesting and straightforward pattern.",
          "visskills": 4,
          "statsskills": 7,
          "mathskills": 7,
          "drawskills": 6,
          "compskills": 6,
          "progskills": 4,
          "cgskills": 5,
          "hciskills": 5,
          "uxskills": 5
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "Interests\n- webdesign\n- finance\n-languages\n\nHobbies\n-dance\n-travelling \n-soccer",
          "tolearn": "An effective way to ingage ones audience and how to display important information in a way that portrays its meaning the most effective. ",
          "visskills": 4,
          "statsskills": 7,
          "mathskills": 6,
          "drawskills": 6,
          "compskills": 7,
          "progskills": 6,
          "cgskills": 1,
          "hciskills": 6,
          "uxskills": 7
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "Master student in Computer Science with Visualization as orientation.",
          "tolearn": "How to Visualize data Hans Rosling style!",
          "visskills": 5,
          "statsskills": 2,
          "mathskills": 5,
          "drawskills": 5,
          "compskills": 10,
          "progskills": 8,
          "cgskills": 8,
          "hciskills": 7,
          "uxskills": 3
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "Photography, Shooting movies, Sketching ",
          "tolearn": "What to learn: \n    How to choose certain patterns to visualize different kinds of data?\n    How to measure or compare if the visualize of data reaches target users' satisfaction?\n    \nHow to use:\n    May apply it to some data mining or statistic projects in the future studies to visualize the results. \n\n\n    \n\n",
          "visskills": 6,
          "statsskills": 8,
          "mathskills": 8,
          "drawskills": 7,
          "compskills": 9,
          "progskills": 6,
          "cgskills": 6,
          "hciskills": 5,
          "uxskills": 8
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "I've been very fascinated by computer graphics ever since I started playing computer games as a kid. Gaming is still one of my favorite hobbies. I also like to play chess during my spare time as well as enjoying cross-country skiing during the winter season.",
          "tolearn": "Using computer graphics as a tool of presenting information in such ways that it can be nicely interpreted by the users. I see this as an opportunity to add something to my portfolio and also to widen my knowledge within the field of computer graphics and its' areas of application.",
          "visskills": 7,
          "statsskills": 5,
          "mathskills": 5,
          "drawskills": 3,
          "compskills": 8,
          "progskills": 7,
          "cgskills": 7,
          "hciskills": 9,
          "uxskills": 5
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "I like the idea of a full-stack developer which is why I started in Computer Science and went on to pursue a masters degree in HCI. Interaction design is my main interest but visualization is a fascinating field.\n\nI like graphic design and have some experience working with it, mainly in the motocross business which is another hobby of mine which I also compete in.",
          "tolearn": "I want to learn the process of taking raw data and creating something insightful and beautiful. I want to learn the common methodology and approaches to different types of visualizations.",
          "visskills": 7,
          "statsskills": 5,
          "mathskills": 7,
          "drawskills": 7,
          "compskills": 9,
          "progskills": 6,
          "cgskills": 5,
          "hciskills": 8,
          "uxskills": 7
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "Music and arts have been my passions for as long as I can remember. It is also very important to be in nature. Every year I spend 2 months on an island in Finland where I sail and build things. Furthermore I have a new interest every year. My interests this year is to boulder and do trekking routes. A this moment I'm in Patagonia and have just completed the famous \"W\" route, Torres del Paine. (Don't worry i will be back on Monday!)\nI choose to study media technology because of my passion fort art, engineering and my constant search on gaining new knowledge. During my time at KTH I have also gotten interest in design, programming and startups. Everytime I'm in a group project where I have the chance to learn something new, I will take it. ",
          "tolearn": "mastering information visualisation is useful and can be very powerful. Something we have seen that Hans Rosling is very successful at. I expect to get a deeper insight in how to present different types of information. How to present a lot of information in an easy and interesting way. ",
          "visskills": 7,
          "statsskills": 6,
          "mathskills": 5,
          "drawskills": 7,
          "compskills": 8,
          "progskills": 7,
          "cgskills": 4,
          "hciskills": 4,
          "uxskills": 7
        },
        {
          "degree": "Master in Science",
          "tolearn": "I expect to be able to present and show data/information in a better and more comprehensible way. Hopefully I will also be able learn some kind of visualization skills.",
          "visskills": 3,
          "statsskills": 6,
          "mathskills": 5,
          "drawskills": 3,
          "compskills": 7,
          "progskills": 6,
          "cgskills": 3,
          "hciskills": 3,
          "uxskills": 4
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "My name is Juho and I have skills in creative and technical side of designing usable UIs.\n\nI am interested in traveling, nature, technology, public speaking and crafts of all kinds. I am also interested in computer animation(moving images), design and entrepreneurship. \n\nIn a free time I play the guitar and visit places, go trekking and biking. I am interesting in learning to do sculpting. ",
          "tolearn": "I would like to learn to represent and analyze data in visualizations in a meaningful and sophisticated way. I also would like to learn more about user centered process and enrich Graphic Design skills.\n\nI wish that we could use visualization data in the presentations in the future and also add the visualizations to videos and documents. To build top notch online applications and interacting with mobile devices. Something to show: portfolio, building a team for entrepreneurial purposes.",
          "visskills": 8,
          "statsskills": 6,
          "mathskills": 4,
          "drawskills": 9,
          "compskills": 8,
          "progskills": 7,
          "cgskills": 6,
          "hciskills": 7,
          "uxskills": 8
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "Hiho!\n\nI am a pretty active guy that likes to test new things in order to really find out who I am and what I enjoy doing. Overall I like games, which ranges from playing video games to play badminton, in which i compete and i´ve been dancing swing for some years. I´m kind of interested in interior design and design overall and i've been spending some time in illustrator and autocad and some other artistic programs and i'm heading in the direction that I want to learn more about web programming and webdesign. ",
          "tolearn": "I expect to learn how do visualize things in more ways than a do now and to get different kinds of perspectives on how other would visualize things and I think i will learn in by getting tips of software's to use and then learn by doing and then compare with the other student. ",
          "visskills": 6,
          "statsskills": 6,
          "mathskills": 3,
          "drawskills": 9,
          "compskills": 9,
          "progskills": 3,
          "cgskills": 1,
          "hciskills": 2,
          "uxskills": 2
        },
        {
          "degree": "Master in Science",
          "tolearn": "I expect to become a better programmer by programming more.\nBe able to better visualise with the data I've gotten and learn how to properly gather that data in the first place.\nWhat an ideal group actually is.\nLearn more about using d3.js.\nLearn what types of different visualisations works for. How is the data clearer when presented depending on the information and target group?\n\nIt doesn't end with just having data. You also have to know how to use it and that is what I expect to use it for. ",
          "visskills": 4,
          "statsskills": 3,
          "mathskills": 5,
          "drawskills": 6,
          "compskills": 7,
          "progskills": 3,
          "cgskills": 1,
          "hciskills": 1,
          "uxskills": 8
        },
        {
          "degree": "Master in Science",
          "tolearn": "I expect to get a comprehensive tool set for visualizing complex data in meaningful and beautiful ways. I also expect to get the opportunity to work with interseting people with many different skillsets.",
          "visskills": 4,
          "statsskills": 5,
          "mathskills": 5,
          "drawskills": 3,
          "compskills": 8,
          "progskills": 5,
          "cgskills": 2,
          "hciskills": 3,
          "uxskills": 4
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "My name is Jonathan Söderin and I'm 22 years old. I'm the oldest of five brothers and I one of my hobbies are video games. I play both on the PS4, Xbox One and on the PC, I love playing with others since I am a very social person. I also love socializing offline and therefore I have been active in the reception here at media technology where I am studying. 2015 was the third year I was active in the reception and this time I was head of the reception and planned the whole thing together with two others. I love working in projects so this was the perfect opportunity for me to work in a way I love with something I love.",
          "tolearn": "I expect to learn how to effectively show information in a way that makes it easy to understand for others and in a way that has impact. I expect to further develop my coding skills, something I really hope to get out from this course.\n\nI expect that what I learn in this course will be good to use in my future work, (hopefully as a projectleader), but also in general.",
          "visskills": 4,
          "statsskills": 6,
          "mathskills": 6,
          "drawskills": 4,
          "compskills": 8,
          "progskills": 3,
          "cgskills": 1,
          "hciskills": 7,
          "uxskills": 6
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "I am quite a creative person and I am very curious. This is why all creative fields interest me and I've tried out most of them. I love drawing and I'd say I'm alright, not an expert but decent. I've been singing since the day I learned how to speak and music is one of my interests. I love working in teams and projects because I am drawn to people and creepily enough like to observe behavioural patterns within groups. In my free time I play a lot of video games and have done that since a young age. When I'm not gaming I read books, lots of them, mostly romatic novels, fantasy and mystery. I really like to work with my hands and especially fix physical things that are broken. There is something satisfactory in screwing in that last screw and knowing it will work. ",
          "tolearn": "I expect to get the tools to be able to, in my future line of work, in an easy and understandable way decribe information, networks etc. for a group of people who are not as familiar with the data as I am. I wish to learn the tools of how data and information should be described/visualized so that trends easily can be observed by others. ",
          "visskills": 2,
          "statsskills": 4,
          "mathskills": 6,
          "drawskills": 8,
          "compskills": 6,
          "progskills": 4,
          "cgskills": 1,
          "hciskills": 3,
          "uxskills": 5
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "My main hobbies that i do regularly is photography (can't live without photoshop) and handball.  More recently (2 years back) thanks to KTH i have learned that i really love coding and especially the web-aspect of code. ",
          "tolearn": "How to in a practical way visualize information in the best way and also along the way learn about different tools to do so. I hope i can use what I have learned in a portfolio and hopefully it will expand my field in code/art etc.  ",
          "visskills": 4,
          "statsskills": 2,
          "mathskills": 5,
          "drawskills": 7,
          "compskills": 10,
          "progskills": 7,
          "cgskills": 5,
          "hciskills": 6,
          "uxskills": 8
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "Programming. \nPlay games, both computer and board games.\nMaking computer games.",
          "tolearn": "How to turn data´that is hard to understand into something easy and intuitive. I also want to make cool shit. ",
          "visskills": 7,
          "statsskills": 4,
          "mathskills": 5,
          "drawskills": 7,
          "compskills": 9,
          "progskills": 4,
          "cgskills": 5,
          "hciskills": 9,
          "uxskills": 4
        },
        {
          "degree": "Master in Science",
          "tolearn": "I expect to improve my programming skills to create things I am proud of and could show to others. ",
          "visskills": 3,
          "statsskills": 1,
          "mathskills": 4,
          "drawskills": 5,
          "compskills": 5,
          "progskills": 4,
          "cgskills": 2,
          "hciskills": 3,
          "uxskills": 8
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "I have taken a course called Information Design before, and we mainly used PS/AI to make Infographics. I found information visualisation interesting during that course, and that's one reason why I register this course.\nMy biggest hobby is dancing. I learned from the internet, record videos and upload them. Though I can't indicate the type of dance and it's always hard to explain what exactly it is and why I do so.",
          "tolearn": "I would like to learn anything about information visualisation and use them to make brilliant stuffs.",
          "visskills": 4,
          "statsskills": 3,
          "mathskills": 5,
          "drawskills": 7,
          "compskills": 7,
          "progskills": 1,
          "cgskills": 3,
          "hciskills": 3,
          "uxskills": 7
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "I am a computer nerd and fitness freak. That's basically it :-)",
          "tolearn": "My idea is that no information is informative of it can't be visualilzed in a pedagogical manner. I hope to get understanding and experience of how to do this. Also expand my skills in visual programming, an area that has been lacking during my years. ",
          "visskills": 5,
          "statsskills": 5,
          "mathskills": 6,
          "drawskills": 2,
          "compskills": 7,
          "progskills": 8,
          "cgskills": 3,
          "hciskills": 4,
          "uxskills": 4
        },
        {
          "degree": "Master in Science",
          "aboutyourself": "Hi,\nI work as a full time software engineer and do iOS apps for almost 7 years. I'm not able to complete all the homeworks with big succes but I'm trying my best.\n\nThanks,\nAlper",
          "tolearn": "I think information visualization is in everywhere. I'd like to use it in personal projects, I'm mostly interested in productivity apps and games",
          "visskills": 4,
          "statsskills": 3,
          "mathskills": 4,
          "drawskills": 4,
          "compskills": 4,
          "progskills": 6,
          "cgskills": 4,
          "hciskills": 4,
          "uxskills": 4
        }
      ];

      $scope.groupData = [
        {
          "numberOfStudents": 6,
          "students": [0,1,2,3,4,5],
          "averageScore": 0
        }
      ];

      $scope.selectedGroupData = [];
      var i = 0;
      var sum = 0;
      for(var student in $scope.groupData[$scope.selectedGroup].students){
        $scope.selectedGroupData[i] = [
          $scope.studentData[student].visskills,
          $scope.studentData[student].statsskills,
          $scope.studentData[student].mathskills,
          $scope.studentData[student].compskills,
          $scope.studentData[student].progskills,
          $scope.studentData[student].cgskills,
          $scope.studentData[student].hciskills,
          $scope.studentData[student].uxskills
        ];
        sum = $scope.studentData[student].visskills +
            $scope.studentData[student].statsskills +
            $scope.studentData[student].mathskills +
            $scope.studentData[student].compskills +
            $scope.studentData[student].progskills +
            $scope.studentData[student].cgskills +
            $scope.studentData[student].hciskills +
            $scope.studentData[student].uxskills;
        i++;
      }
      $scope.groupData[$scope.selectedGroup].averageScore = sum / 6 / 8;
      console.log($scope.groupData[$scope.selectedGroup].averageScore);
  }]);
